# Generated by Django 4.2.6 on 2023-10-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures')),
                ('country', models.CharField(max_length=250, verbose_name='country')),
                ('state', models.CharField(max_length=250, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('Timezone', models.CharField(max_length=250, verbose_name='Timezone')),
                ('LinkedIn', models.CharField(max_length=250, verbose_name='LinkedIn')),
                ('ShortCV', models.TextField(blank=True, null=True)),
                ('CurrentEmployment', models.CharField(max_length=250, verbose_name='CurrentEmployment')),
                ('MentoringRole', models.CharField(blank=True, max_length=250, null=True)),
                ('ModeofCommunication', models.CharField(blank=True, max_length=250, null=True)),
                ('PreviousExperience', models.CharField(blank=True, max_length=250, null=True)),
                ('DevelopmentAreas', models.TextField(blank=True, null=True)),
                ('OtherAreas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', editable=False, length=5, max_length=40, prefix='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='orgainizations/logos')),
                ('OrganizationName', models.CharField(max_length=250, verbose_name='OrgName')),
                ('Description', models.TextField(verbose_name='description')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('Active', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
