# Generated by Django 4.2.2 on 2023-10-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='orgainizations/logos')),
                ('OrganizationName', models.CharField(max_length=250, verbose_name='OrgName')),
                ('Description', models.TextField(verbose_name='description')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
