# Generated by Django 4.2.6 on 2023-10-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
