# Generated by Django 4.2.6 on 2023-10-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
