# Generated by Django 4.2.6 on 2023-10-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unique_id',
            new_name='AffiliatedOrg',
        ),
    ]
