# Generated by Django 4.2.2 on 2023-10-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures')),
                ('country', models.CharField(max_length=250, verbose_name='country')),
                ('state', models.CharField(max_length=250, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('Timezone', models.CharField(max_length=250, verbose_name='Timezone')),
                ('LinkedIn', models.CharField(max_length=250, verbose_name='LinkedIn')),
                ('ShortCV', models.TextField(blank=True, null=True)),
                ('CurrentEmployment', models.CharField(max_length=250, verbose_name='CurrentEmployment')),
                ('MentoringRole', models.CharField(choices=[('Mentee', 'Mentee'), ('Mentor', 'Mentor')], max_length=250)),
                ('ModeofCommunication', models.CharField(blank=True, max_length=250, null=True)),
                ('PreviousExperience', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=250)),
                ('OtherAreas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
