# Generated by Django 4.2.5 on 2023-10-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='DevelopmentAreas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='MentoringRole',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='PreviousExperience',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
